#!/usr/bin/env python3
"""
Quick Streamlit dashboard to review image inventory generated by scripts/extract_images.py.

Usage:
    streamlit run analytics/app.py -- --csv image-report.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import streamlit as st


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize HubSpot image inventory.")
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("image-report.csv"),
        help="Path to the CSV generated by scripts/extract_images.py",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    st.set_page_config(page_title="HubSpot Image Inventory", layout="wide")
    st.title("HubSpot Image Inventory")

    if not args.csv.exists():
        st.error(f"CSV '{args.csv}' not found. Run extract_images.py first.")
        return

    df = pd.read_csv(args.csv)

    st.sidebar.header("Filters")
    unique_pages = sorted(df["page"].dropna().unique())
    selected_pages = st.sidebar.multiselect("Pages", unique_pages, default=unique_pages)
    unique_folders = sorted(df["hubspot_folder"].dropna().unique())
    selected_folders = st.sidebar.multiselect("HubSpot folders", unique_folders)

    filtered = df[df["page"].isin(selected_pages)]
    if selected_folders:
        filtered = filtered[filtered["hubspot_folder"].isin(selected_folders)]

    st.metric("Total images", len(df))
    st.metric("Images (filtered)", len(filtered))

    st.subheader("Images by HubSpot Folder")
    folder_counts = filtered.groupby("hubspot_folder")["src"].count().sort_values(ascending=False)
    st.bar_chart(folder_counts)

    st.subheader("Image Table")
    st.dataframe(
        filtered[
            [
                "page",
                "hubspot_folder",
                "hubspot_path",
                "src",
                "alt",
                "title",
                "nearest_heading",
            ]
        ]
    )


if __name__ == "__main__":
    main()

