import { useEffect, useMemo, useState } from "react";
import Papa from "papaparse";
import { motion } from "framer-motion";
import { ImageTable, type ImageRecord } from "./components/ImageTable";

interface RawRecord extends Partial<ImageRecord> {
  [key: string]: string | undefined;
}

function useCsvData(path: string) {
  const [data, setData] = useState<ImageRecord[]>([]);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");

  useEffect(() => {
    setStatus("loading");
    Papa.parse<RawRecord>(path, {
      header: true,
      download: true,
      skipEmptyLines: true,
      complete: (results) => {
        const rows =
          results.data?.map((row) => ({
            page: row.page ?? "",
            hubspot_folder: row.hubspot_folder ?? "",
            hubspot_path: row.hubspot_path ?? "",
            src: row.src ?? "",
            alt: row.alt ?? "",
            title: row.title ?? "",
            nearest_heading: row.nearest_heading ?? "",
          })) ?? [];
        setData(rows);
        setStatus("idle");
      },
      error: () => setStatus("error"),
    });
  }, [path]);

  return { data, status };
}

function FilterChip({
  count,
  label,
}: {
  count: number;
  label: string;
}) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 shadow-sm">
      <p className="text-xs uppercase text-slate-400">{label}</p>
      <p className="text-2xl font-semibold text-slate-900">{count}</p>
    </div>
  );
}

const heroVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};

export default function App() {
  const { data, status } = useCsvData("/image-report.csv");
  const [search, setSearch] = useState("");
  const [selectedFolder, setSelectedFolder] = useState<string | null>(null);
  const [selectedPage, setSelectedPage] = useState<string | null>(null);

  const folders = useMemo(() => {
    const unique = Array.from(new Set(data.map((d) => d.hubspot_folder).filter(Boolean)));
    return unique.sort();
  }, [data]);

  const pages = useMemo(() => {
    const unique = Array.from(new Set(data.map((d) => d.page).filter(Boolean)));
    return unique.sort();
  }, [data]);

  const filtered = useMemo(() => {
    return data.filter((row) => {
      const matchesSearch =
        !search ||
        row.alt.toLowerCase().includes(search.toLowerCase()) ||
        row.nearest_heading.toLowerCase().includes(search.toLowerCase()) ||
        row.hubspot_folder.toLowerCase().includes(search.toLowerCase());
      const matchesFolder = !selectedFolder || row.hubspot_folder === selectedFolder;
      const matchesPage = !selectedPage || row.page === selectedPage;
      return matchesSearch && matchesFolder && matchesPage;
    });
  }, [data, search, selectedFolder, selectedPage]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      <div className="mx-auto w-full max-w-6xl px-4 py-10">
        <motion.div
          initial="hidden"
          animate="visible"
          variants={heroVariants}
          className="mb-10 flex flex-col gap-4"
        >
          <p className="text-sm font-semibold uppercase tracking-[0.3em] text-slate-400">
            HubSpot Assets
          </p>
          <h1 className="text-4xl font-black text-slate-900">
            Image Inventory Dashboard
          </h1>
          <p className="text-lg text-slate-600">
            Interactive explorer for the `image-report.csv` generated by our
            HubSpot parser. Filter by page, folder, or search text to zero in on
            problem spots fast.
          </p>
        </motion.div>

        <div className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <FilterChip label="Total Images" count={data.length} />
          <FilterChip label="Unique Pages" count={pages.length} />
          <FilterChip label="Unique Folders" count={folders.length} />
          <FilterChip label="Filtered" count={filtered.length} />
        </div>

        <div className="mb-8 grid gap-4 lg:grid-cols-[1fr,1fr,1fr]">
          <input
            type="search"
            placeholder="Search by alt text, heading, or folder..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="rounded-xl border border-slate-200 px-4 py-3 text-sm shadow-sm focus:border-slate-400 focus:outline-none"
          />
          <select
            className="rounded-xl border border-slate-200 px-4 py-3 text-sm shadow-sm focus:border-slate-400 focus:outline-none"
            value={selectedFolder ?? ""}
            onChange={(e) => setSelectedFolder(e.target.value || null)}
          >
            <option value="">All folders</option>
            {folders.map((folder) => (
              <option key={folder} value={folder}>
                {folder}
              </option>
            ))}
          </select>
          <select
            className="rounded-xl border border-slate-200 px-4 py-3 text-sm shadow-sm focus:border-slate-400 focus:outline-none"
            value={selectedPage ?? ""}
            onChange={(e) => setSelectedPage(e.target.value || null)}
          >
            <option value="">All pages</option>
            {pages.map((page) => (
              <option key={page} value={page}>
                {page}
              </option>
            ))}
          </select>
        </div>

        {status === "loading" ? (
          <p className="text-center text-slate-500">Loading CSV...</p>
        ) : status === "error" ? (
          <p className="text-center text-red-500">
            Failed to load CSV. Ensure image-report.csv exists in /analytics/ui/public.
          </p>
        ) : (
          <ImageTable images={filtered} />
        )}
      </div>
    </div>
  );
}

